"""Add difficulty to Quiz

Revision ID: e199940fede6
Revises: 0db0d0e8c85e
Create Date: 2025-02-20 17:34:25.836535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e199940fede6'
down_revision = '0db0d0e8c85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=10), nullable=False))
        batch_op.drop_column('difficult')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficult', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
